apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: spark-submit-workflow-template
spec:
  entrypoint: spark-submit-workflow
  arguments:
    parameters:
      - name: numberOfInstance
        valueFrom:
          configMapKeyRef:
            name: spark-submit-parameters
            key: numberOfInstance
      - name: master
        valueFrom:
          configMapKeyRef:
            name: spark-submit-parameters
            key: master
      - name: imageName
        valueFrom:
          configMapKeyRef:
            name: spark-submit-parameters
            key: imageName
      - name: jarName
        valueFrom:
          configMapKeyRef:
            name: spark-submit-parameters
            key: jarName
      - name: appInputParameters
        valueFrom:
          configMapKeyRef:
            name: spark-submit-parameters
            key: appInputParameters
      - name: sparkCmd
        valueFrom:
          configMapKeyRef:
            name: spark-submit-parameters
            key: sparkCmd
  templates:
  - name: spark-submit-workflow
    inputs:
      parameters:
        - name: appName
        - name: master
        - name: className
        - name: numberOfInstance
        - name: imageName
        - name: jarName
        - name: sparkCmd
        - name: appInputParameters
    container:
      securityContext:
        runAsUser: 0
      command: [
          "/bin/sh",
          "-c",
          "{{inputs.parameters.sparkCmd}}"
      ]
      image: leventsparktestk8cr.azurecr.io/jem:latest
      imagePullPolicy: Always
      resources: {}
    imagePullSecrets:
      - name: regcred
