apiVersion: v1
kind: ConfigMap
metadata:
  name: spark-submit-parameters
  labels:
    workflows.argoproj.io/configmap-type: Parameter
data:
   master: "k8s://https://kubernetes.docker.internal:6443"
   imageName: "jem:latest"
   jarName: "JemKubernetes-3.3.1.jar"
   numberOfInstance: "2"
   appInputParameters: "<<required params>>"
   sparkCmd: "/opt/spark/bin/spark-submit \
      --master {{inputs.parameters.master}} \
      --deploy-mode cluster --name {{inputs.parameters.className}} \
      --class {{inputs.parameters.className}} \
      --conf spark.executor.instances={{inputs.parameters.numberOfInstance}} \
      --conf spark.kubernetes.namespace=argo \
      --conf spark.kubernetes.container.image={{inputs.parameters.imageName}}
      --conf spark.kubernetes.authenticate.driver.serviceAccountName=default \
      --driver-java-options=-Djem.snowflake.conf.path=/opt/spark/work-dir/snowflake/snowflake.props \
      local:///opt/spark/work-dir/jem/{{inputs.parameters.jarName}} {{inputs.parameters.appInputParameters}} {{inputs.parameters.appName}} "
